### ISSUE TITLE
help me understand this. Thanks. 

### ISSUE THREAD

**Issue by kundeng** [solita/docker-systemd-ssh#1]
what is the purpose of this:
RUN mkdir /root/.ssh && \
  touch /root/.ssh/authorized_keys && \
  chmod 700 /root/.ssh && \
  chmod 600 /root/.ssh/authorized_keys

If you are preparing to mount authorized_keys from the host file system,  the mounting happens AFTER the above RUN and before  entrypoint/CMD.  So the permission will be whatever the host file has.   On the docker host,  I am not running as root but a docker user, so this would not work. 

I guess one  could use a host file or  an ENV in the entrypoint script, and write it to the authorized_keys file there.  Is that what you have in mind?

**Comment by noidi** [comment]
The idea is that you can add a public key to the file when building a derived image.
